### ISSUE TITLE
Modifying role doesn't reflect on vault

### ISSUE THREAD

**Issue by raoofm** [banzaicloud/bank-vaults#543] opened 2019-07-08 16:40 UTC
**Describe the bug**
Modifying role doesn't reflect on vault (tried kubernetes backend)

**To Reproduce**
bankVaults: 0.4.17-rc.4
vault: 1.1.3

create a kubernetes role using externalConfig in vault crd
Modify the bound_cidrs list

**Expected behavior**
vault configurer should reconfigure the role but does not.

**Comment by bonifaido** [comment] 2019-07-09 06:08
Could you please post your exact CR snippet as YAML?

**Comment by raoofm** [comment] 2019-07-09 21:56
```
externalConfig:
    auth:
    - type: kubernetes
      config:
        token_reviewer_jwt: eyJxxxxxxx
        kubernetes_ca_cert: |
          -----BEGIN CERTIFICATE-----
          MIIC1zCCAb+gAwIBAgIQMA3BMbdwlbbfSlq78mD3bjANBgkqhkiG9w0BAQsFADAV
          ................................................................
          4hIu+FuRm7RBIZJ0yrAXVsKoULoBk13wZK2nhLDvDyKfyLlWhQ/r+EZWHrvU+PZ5
          KvFiuwh8ZxH4+c8=
          -----END CERTIFICATE-----
        kubernetes_host: https://api.k8s.dev.example.net
      roles:
        - name: vault-proxy
          bound_service_account_names: vault-proxy
          bound_service_account_namespaces: vault
          bound_cidrs: 10.x.x.0/20, 100.x.x.0/11
          policies: approle
          ttl: 12h
          max_ttl: 24h
```
modified the bound_cidrs and added one more range

bound_cidrs: 10.x.x.0/30, 100.x.x.0/11, 10.7.x.x/31

**Comment by bonifaido** [comment] 2019-07-10 07:27
I have successfully added the 3rd row to the auth config as well, and the changes have been reflected on Vault. Do you have any special in the configurer logs?

```
vault read auth/kubernetes/role/default                                   
Key                                 Value
---                                 -----
bound_cidrs                         ["\"10.x.x.0/20\"" "\"100.x.x.0/11\""]
bound_service_account_names         [default vault-secrets-webhook]
bound_service_account_namespaces    [default vswh]
max_ttl                             0s
num_uses                            0
period                              0s
policies                            [allow_secrets]
ttl                                 1h
```

Edit the config file then `kubectl apply -f cr.yaml` again:

```
 vault read auth/kubernetes/role/default                                   
Key                                 Value
---                                 -----
bound_cidrs                         ["\"10.x.x.0/20\"" "\"100.x.x.0/11\"" "\"10.7.x.x/31\""]
bound_service_account_names         [default vault-secrets-webhook]
bound_service_account_namespaces    [default vswh]
max_ttl                             0s
num_uses                            0
period                              0s
policies                            [allow_secrets]
ttl                                 1h
```

**Comment by bonifaido** [comment] 2019-07-16 14:37
Closing, because of we were not able to reproduce the issue.

**Closed by bonifaido** 2019-07-16 14:37 UTC
Labels: configurer
