### ISSUE TITLE
Discussion: Handle vault HA in true sense | multi DC/region with backup and restore

### ISSUE THREAD

**Issue by raoofm** [banzaicloud/bank-vaults#359] opened 2019-03-14 09:13 UTC
**Is your feature request related to a problem? Please describe.**
Handle vault HA in true sense | multi DC/region with backup and restore

**Describe the solution you'd like**
It could be replication of backend completely like a DR or can be a static (prefix/secret) replication with independent leases that adds scalability.

**Additional context**
not just HA as in #342 but a global HA vault

**Comment by raoofm** [comment] 2019-03-20 16:00
This will be a big win as no one offers it cleanly. I did some background research work and can explain if we hop on a call in the slack channel or if I find some time will put some my rough ideas on paper.

**Comment by bonifaido** [comment] 2019-03-20 20:29
Hi @raoofm, yes please do so thanks, we appreciate it! Next week would be good for a call again on Slack/Zoom if it's okay for you, we can discuss it on the chat.

**Comment by bonifaido** [comment] 2019-03-20 20:35
Isn't this the duplicate of https://github.com/banzaicloud/bank-vaults/issues/316 ?

**Comment by bonifaido** [comment] 2019-10-14 11:19
Duplicate of #316

**Closed by bonifaido** 2019-10-14 11:19 UTC
Labels: HA, community, wontfix
