### ISSUE TITLE
statefulset immutable fields changes in Vault CRD are not taken into account

### ISSUE THREAD

**Issue by jordanjean** [banzaicloud/bank-vaults#1121] opened 2020-09-28 09:45 UTC
# Description

When I update the service account name in my Vault object, the change is not propagated by the operator in the subsequent vault StatefulSets and vault-configurer Deployment.

# Steps to reproduce

1. Deploy the Vault Operator chart v1.4.2
2. Create a Vault object along with RBAC objects (including the ServiceAccount)
3. Change the name of the ServiceAccount and update the ServiceAccount field in the Vault object
4. See vault StatefulSets and vault-configurer deployment are still using the obsolete ServiceAccount

Maybe the operator should delete and recreate the vault StatefulSets and update the vault-configurer Deployment when such changes are detected.

**Comment by bonifaido** [comment] 2020-09-28 11:25
What Kubernetes version are you using @jordanjean, I can't reproduce this on 1.16 with the latest Bank-Vaults code with the exact same steps you described.

**Comment by jordanjean** [comment] 2020-09-28 11:59
Hello @bonifaido,

I'm running Kubernetes 1.16.9 and Bank-Vault 1.4.2.

After updating the ServiceAccount of my Vault object (through Helm) I can see reconciling errors in the Operator logs saying it cannot update the StatefulSets (which is normal as Kubernetes does not allow changes of fields other than Replicas and UpdateStrategy).

**Comment by bonifaido** [comment] 2020-09-28 12:19
Allowing the mutation of the `template` (where `serviceAccount` is configurable) field was added a before 1.16:

https://github.com/kubernetes/kubernetes/blob/release-1.16/pkg/apis/apps/validation/validation.go#L144

Could you please post the exact error message from the logs of the operator?

**Comment by jordanjean** [comment] 2020-09-28 15:17
This is the error in the operator:
```
{"level":"error","ts":1601298919.9049187,"logger":"controller","msg":"Reconciler error","controller":"vault-controller","name":"vault","namespace":"myapp-vault","error":"failed to create/update StatefulSet: StatefulSet.apps \"vault\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:237\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90"}
```

And this is the diff between the manifests of the Vault object before the upgrade and the one after the upgrade:

```
8c8
<   generation: 4
---
>   generation: 3
13,14c13,14
<     app.kubernetes.io/version: 2.2.0
<     helm.sh/chart: mychart-2.2.0
---
>     app.kubernetes.io/version: 2.1.0
>     helm.sh/chart: mychart-2.1.0
17c17
<   resourceVersion: "504429"
---
>   resourceVersion: "501051"
166c166
<   serviceAccount: newName
---
>   serviceAccount: oldName
199a200
>       creationTimestamp: null
204,205c205,206
<         app.kubernetes.io/version: 2.2.0
<         helm.sh/chart: mychart-2.2.0
---
>         app.kubernetes.io/version: 2.1.0
>         helm.sh/chart: mychart-2.1.0
212a214
>     status: {}
```

The point is that the upgrades of our Vault object is managed by Helm and we add labels `app.kubernetes.io/version: <version>` and `helm.sh/chart: mychart-<version>` to our Vault object volumeClaimTemplate. In the diff we can see that the labels are changed because the chart version changed from 2.1.0 to 2.2.0. That is what Kubernetes does not like.

While I was getting errors speaking of wrong ServiceAccount name at the Kubernetes level, the ServiceAccount field was indeed not involved with the StatefulSet upgrade error, but Helm labels were.

**Comment by bonifaido** [comment] 2020-09-29 12:50
No problem!

So it boils down to the fact that volumeClaimTemplates in StatefulSets can't be updated, I don't think we plan to support that in the near future. So I'm closing this one now if you encounter any issues please feel free to open another ticket, or reopen this one.

Maybe it would be worth not to add the Helm version labels to the volumeClaimTemplate labels and you would leave the whole process distraction-free with this. Anyhow if you stick to leaves the labels there I would delete the StatefulSet with `--cascase=false` and scale down the operator to 0 replicas, so it will not recreate the StatefulSet in the middle of the upgrade process before just upgrading even with Helm. Then scale it back to the original size. With this procedure, you get no downtime.

Thanks for the heads up!

**Closed by bonifaido** 2020-09-29 12:50 UTC
