### ISSUE TITLE
Deploying size > 1 with raft storage produces error

### ISSUE THREAD

**Issue by funkypenguin** [banzaicloud/bank-vaults#716] opened 2019-10-24 08:35 UTC
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
I tried to apply the raft storage example detailed at https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr-raft.yaml

The operator produced the following error:  `failed to fabricate StatefulSet: more than 1 replicas are not supported without HA storage backend`

**Expected behaviour**:
Operator would deploy statefulset of 3, with raft storage

**Steps to reproduce the bug**:

1. Deploy vault-operator using bank-vaults 0.5.3
2. Apply `cr-raft.yaml` (above)

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.16.0
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): Bare-metal
- bank-vaults version (e.g. 0.4.17): 0.5.3
- Install method (e.g. helm or static manifests): Helm without tiller
- Logs from the misbehaving component (and any other relevant logs):

```
{"level":"info","ts":1571905573.274615,"logger":"controller_vault","msg":"Reconciling Vault","Request.Namespace":"cluster-vault","Request.Name":"cluster-vault"}
{"level":"error","ts":1571905576.69713,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"vault-controller","request":"cluster-vault/cluster-vault","error":"failed to fabricate StatefulSet: more than 1 replicas are not supported without HA storage backend","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/internal/controller/controller.go:217\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:88"}
```

/kind bug

**Comment by bonifaido** [comment] 2019-10-24 09:15
Hi @funkypenguin, thanks for reporting this. This is definitely a small bug in the operator, I'm going to fix it.

**Comment by bonifaido** [comment] 2019-10-24 09:15
But out of curiosity, why would someone create a raft storage cluster with one replica? :)

**Comment by funkypenguin** [comment] 2019-10-24 09:47
Well that's exactly it :) I tried to create a raft storage cluster with replicas, but the operator wouldn't let me.

I _may_ have discovered a related bug  by following cr-raft.yaml too, although it may be the result of creating the aforementioned 1-replica-raft-storage... when `size` is set to 1, the `volumeClaimTemplates` section seems to be ignored, and the 1-replica statefulset won't start,  because the volume can't be found.  

Thanks for the attention!
D

**Comment by bonifaido** [comment] 2019-10-24 09:51
Which version of the operator are you using? I think the example is still broken since it uses latest images of bank-vaults, but the raft will be released only in 0.6.0. Could you please try with an operator of version `0.6.0-rc.2` and also please change the bank-vaults image in the cr-raft.yaml to `0.6.0-rc.2` as well?

**Comment by funkypenguin** [comment] 2019-10-24 10:33
I tested with 0.6.0-rc.2, and the fault reported above is gone. I have `size: 3`, and the operator no longer complains about my not having HA storage.

Vault, on the other hand, _is_ complaining about the VolumeMountTemplate:

```
Error initializing storage of type raft: failed to create fsm: open /vault/raft/vault.db: permission denied
```

**Comment by bonifaido** [comment] 2019-10-24 11:00
I can't reproduce that in my Docker for Mac Kubernetes cluster right now. What kind of Persistent Volumes are you using? On which cloud provider?

**Comment by funkypenguin** [comment] 2019-10-24 17:01
I’m using rook-ceph, on bare metal. It’s behaved perfectly normally (until now!) :)

**Comment by funkypenguin** [comment] 2019-10-24 19:35
It seems to be related to using VolumeMountTemplates. The `vault` process runs as UID 100, but the mounted path is owned by root:

```
/ # ls -la /vault/raft/
total 0
drwxr-xr-x    2 root     root             6 Oct 24 17:38 .
drwxr-xr-x    1 vault    vault           29 Oct 24 19:32 ..
/ # ps | grep vault
    6 vault     0:00 vault server -config=/vault/config -dev-root-token-id= -dev-listen-address=0.0.0.0:8200
   64 root      0:00 grep vault
/ #
```

**Comment by funkypenguin** [comment] 2019-10-24 19:59
OK, I think the issue is that vault runs as UID 100, so in a statefulset situation when using VolumeMountTemplate, we need to add:

`fsGroup: 100` to the **pod** spec (not the container spec) to the statefulset.

Is there an existing mechanism to set this?

Thanks!
D

**Comment by bonifaido** [comment] 2019-10-31 10:15
PodSpec is configurable in the Vault CR I'm just not sure if this is an issue in your environment or an issue in bank-vaults globally because I still can't reproduce the error. Please check:

https://github.com/banzaicloud/bank-vaults/blob/b0180e5072fe12b061a010e20e66f85a248fc138/operator/pkg/apis/vault/v1alpha1/vault_types.go#L164

**Comment by bonifaido** [comment] 2019-10-31 11:29
Just managed to reproduce this.

**Comment by bonifaido** [comment] 2019-10-31 13:32
I have added `fsGroup: 100` to the `securityContext` the pods seem to have this now, but still the same issue.

**Comment by pbalogh-sa** [comment] 2019-11-13 08:50
Please try to use `fsGroup: 1000` because the vault group id is 1000 in the vault container.

**Closed** 2019-11-13 12:53 UTC
Labels: operator, storage
