### ISSUE TITLE
In vault-env mutatingwebhook usage, "vault:login" special variable causes 'namespace not authorized'

### ISSUE THREAD

**Issue by PeterGrace** [banzaicloud/bank-vaults#1177] opened 2020-11-05 21:18 UTC
**Describe the bug**:
When creating a Deployment that utilizes bank-vaults vault-env mutatingwebhook, a Deployment that otherwise works fine (can lookup secrets with `vault:PATH#KEY` syntax.)  When creating a VAULT_TOKEN environment variable with "vault:login" value,  errors are emitted:
```
time="2020-11-05T21:04:14Z" level=error msg="failed to request new Vault token" app=vault-env err="Error making API request.\n\nURL: PUT http
s://vault.vault:8200/v1/auth/kubernetes/login\nCode: 500. Errors:\n\n* namespace not authorized"
```

**Expected behaviour**:
VAULT_TOKEN environment variable should contain a VAULT_TOKEN that could be used by the vault cli inside of the container to interact with vault.

**Steps to reproduce the bug**:
1. Create deployment that utilizes vault-env mutatingwebhook, and validate it works with a normal secret lookup.
2. Create a VAULT_TOKEN environment variable, containing "vault:login" in the value field.
3. Validate that "namespace not authorized" is emitted instead of the login token being set properly in VAULT_TOKEN.

**Additional context**:
Thinking originally that this might be due to not enough permissions in my readonly policy, I instead made a special drone role that had the same policy assigned as my administrator account.  This did not change the behavior.

**Environment details**:
- Kubernetes version (e.g. v1.10.2): k3s 1.18.10+k3s1
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): Bare metal
- bank-vaults version (e.g. 0.4.17): 1.7.0
- Install method (e.g. helm or static manifests): kustomize manifests
- Logs from the misbehaving component (and any other relevant logs): No interesting logs in vault server or vault-secret-webhook pods.
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: vault-plugin
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: drone
  name: droneio-plugin-vault
  namespace: drone
  resourceVersion: "73130041"
  selfLink: /apis/apps/v1/namespaces/drone/deployments/droneio-plugin-vault
  uid: dc907cda-2de7-4941-97a6-892ee82d10db
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: vault-plugin
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: drone
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: https://keimvault.vault:8200
        vault.security.banzaicloud.io/vault-role: drone-vault-admin
        vault.security.banzaicloud.io/vault-skip-verify: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: vault-plugin
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: drone
    spec:
      containers:
      - env:
        - name: DRONE_SECRET
          value: vault:kv/data/drone/env#DRONE_SECRET_PLUGIN_TOKEN
        - name: DRONE_DEBUG
          value: "true"
        - name: VAULT_ADDR
          value: https://keimvault.vault:8200
        - name: VAULT_TOKEN
          value: vault:login
        image: docker.io/drone/vault:latest
        imagePullPolicy: Always
        name: drone-vault
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: droneio-server
      serviceAccountName: droneio-server
      terminationGracePeriodSeconds: 30
```

/kind bug

**Comment by PeterGrace** [comment] 2020-11-06 15:41
@bonifaido mentioned in Slack that the "namespace not authorized" error is being emitted from vault, further leading me to believe this could be a policy setting issue.  I'm not sure which policy would be needed, however -- both my admin token, and my readonly token, were set to create/read/update `auth/token*` as a test and that didn't seem to make a difference.  Hopefully someone else stumbles on this issue and might know better.

**Comment by bonifaido** [comment] 2020-11-09 08:51
I'm still not able to reproduce this, I have tried the following setup:

```bash
helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com
helm upgrade --install vault-secrets-webhook banzaicloud-stable/vault-secrets-webhook
helm upgrade --install vault-operator banzaicloud-stable/vault-operator
kubectl apply -f operator/deploy/rbac.yaml # from the repository
kubectl apply the following deployment -->
```
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-secrets
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-secrets
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
        vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    spec:
      containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "echo $AWS_SECRET_ACCESS_KEY $VAULT_TOKEN && echo going to sleep... && sleep 10000"]
        env:
        - name: AWS_SECRET_ACCESS_KEY
          value: vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY
        - name: VAULT_TOKEN
          value: vault:login
        - name: VAULT_ADDR
          value: https://vault:8200
```

Can you please share all the logs from the failing container? How did you configure the Kubernetes Auth backend in Vault?

**Comment by PeterGrace** [comment] 2020-11-10 13:16
Thank you @bonifaido for having a look.  I cannot replicate your above steps in a brand new cluster, because vault-tls cert does not exist.  Did you create that cert with some additional steps?

In my malfunctioning deployment, the logs for the container are very slim:
```
  $   kubectl logs --prefix droneio-plugin-vault-79f54c8f6d-652rz
[pod/droneio-plugin-vault-79f54c8f6d-652rz/drone-vault] time="2020-11-10T13:10:38Z" level=error msg="failed to request new Vault token" app=vault-env err="Error making API request.\n\nURL: PUT https://keimvault.vault:8200/v1/auth/kubernetes/login\nCode: 500. Errors:\n\n* namespace not authorized"
[pod/droneio-plugin-vault-79f54c8f6d-652rz/drone-vault] time="2020-11-10T13:10:43Z" level=error msg="failed to request new Vault token" app=vault-env err="Error making API request.\n\nURL: PUT https://keimvault.vault:8200/v1/auth/kubernetes/login\nCode: 500. Errors:\n\n* namespace not authorized"
[pod/droneio-plugin-vault-79f54c8f6d-652rz/drone-vault] time="2020-11-10T13:10:45Z" level=fatal msg="failed to create vault clienttimeout [10s] during waiting for Vault token" app=vault-env
```
One interesting item of note -- these errors are coming from drone-vault container, not vault-env or vault-env-copy, so it is possible that the drone.io secret plugin that I am deploying is asking for something more from the vault server than it is authorized to use.   I'm going to investigate this further and I will report back.

**Comment by PeterGrace** [comment] 2020-11-10 13:26
Unfortunately even when I fire up alpine and echo the variables like you've done in the above deployment, I still get these errors:
```
  $   kubectl logs --prefix droneio-test-vault-5c9f5f8685-l6fdd
[pod/droneio-test-vault-5c9f5f8685-l6fdd/alpine] time="2020-11-10T13:22:02Z" level=error msg="failed to request new Vault token" app=vault-env err="Error making API request.\n\nURL: PUT https://keimvault.vault:8200/v1/auth/kubernetes/login\nCode: 500. Errors:\n\n* namespace not authorized"
[pod/droneio-test-vault-5c9f5f8685-l6fdd/alpine] time="2020-11-10T13:22:07Z" level=error msg="failed to request new Vault token" app=vault-env err="Error making API request.\n\nURL: PUT https://keimvault.vault:8200/v1/auth/kubernetes/login\nCode: 500. Errors:\n\n* namespace not authorized"
[pod/droneio-test-vault-5c9f5f8685-l6fdd/alpine] time="2020-11-10T13:22:08Z" level=fatal msg="failed to create vault clienttimeout [10s] during waiting for Vault token" app=vault-env
```
The deployment spec that I used:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: droneio-test-vault
  labels:
    app.kubernetes.io/component: vault-test
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: drone
      app.kubernetes.io/component: vault-test
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: https://keimvault.vault:8200
        vault.security.banzaicloud.io/vault-skip-verify: "true" # Container is missing Trusted Mozilla roots too.
        vault.security.banzaicloud.io/vault-role: "drone-vault-admin"
      labels:
        app.kubernetes.io/name: drone
        app.kubernetes.io/component: vault-test
    spec:
      serviceAccountName: droneio-server
      containers:
        - name: alpine
          image: alpine
          command: ["sh", "-c", "echo $DRONE_SECRET $VAULT_ADDR $VAULT_TOKEN && echo going to sleep... && sleep 10000"]
          env:
          - name: DRONE_SECRET
            value: "vault:kv/data/drone/env#DRONE_SECRET_PLUGIN_TOKEN"
          - name: DRONE_DEBUG
            value: "true"
          - name: VAULT_ADDR
            value: "https://keimvault.vault:8200"
          - name: VAULT_TOKEN
            value: "vault:login"
          securityContext: {}
```

As for my vault config for kubernetes:
```
  $   vault read auth/kubernetes/config
Key                       Value
---                       -----
disable_iss_validation    false
disable_local_ca_jwt      false
issuer                    n/a
kubernetes_ca_cert        <redacted cert material>
kubernetes_host           https://10.43.0.1
pem_keys                  []
```

The drone-vault-admin role that is being bound in the deployment:
```
  $   vault read auth/kubernetes/role/drone-vault-admin
Key                                 Value
---                                 -----
bound_service_account_names         [droneio-server droneio-runner]
bound_service_account_namespaces    [drone]
token_bound_cidrs                   []
token_explicit_max_ttl              0s
token_max_ttl                       0s
token_no_default_policy             false
token_num_uses                      0
token_period                        0s
token_policies                      [admin]
token_ttl                           1h
token_type                          default
```

If you'd like me to paste the policy for `admin` I can do that as well, but that's a big paste.

**Comment by bonifaido** [comment] 2020-11-10 14:22
The only real difference I can spot is the token ttl field is missing (for real?) in your output, compared to the example configured by the configurer (in cr.yaml).

```
vault read auth/kubernetes/role/default
Key                                 Value
---                                 -----
bound_service_account_names         [default vault-secrets-webhook vault]
bound_service_account_namespaces    [default vswh]
policies                            [allow_pki allow_secrets]
token_bound_cidrs                   []
token_explicit_max_ttl              0s
token_max_ttl                       0s
token_no_default_policy             false
token_num_uses                      0
token_period                        0s
token_policies                      [allow_pki allow_secrets]
token_ttl                           1h
token_type                          default
ttl                                 1h
```

How do you configure Vault itself?

**Comment by PeterGrace** [comment] 2020-11-10 15:18
I use terraform to configure Vault.  I notice that you also have a `policies` section where mine does not.  It says in the docs for the vault provider that both "ttl" and "policies" are deprecated for vault >=1.2 and that token_ttl and token_policies are supposed to be used instead (https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/kubernetes_auth_backend_role#deprecated-arguments)

In fact, terraform gripes at me when I try to set both ttl and token_ttl types, so I will have to manually do it and see if that change causes anything to happen.

**Comment by PeterGrace** [comment] 2020-11-10 15:21
Sadly, mimicking your role definition has caused no change:
```
  $   vault read auth/kubernetes/role/drone
Key                                 Value
---                                 -----
bound_service_account_names         [droneio-server droneio-runner]
bound_service_account_namespaces    [drone]
policies                            [default kv-readonly]
token_bound_cidrs                   []
token_explicit_max_ttl              0s
token_max_ttl                       0s
token_no_default_policy             false
token_num_uses                      0
token_period                        0s
token_policies                      [default kv-readonly]
token_ttl                           1h
token_type                          default
ttl                                 1h
  $   kubectl logs droneio-test-vault-5c9f5f8685-g7x8k
time="2020-11-10T15:20:12Z" level=error msg="failed to request new Vault token" app=vault-env err="Error making API request.\n\nURL: PUT https://keimvault.vault:8200/v1/auth/kubernetes/login\
nCode: 500. Errors:\n\n* namespace not authorized"
time="2020-11-10T15:20:17Z" level=error msg="failed to request new Vault token" app=vault-env err="Error making API request.\n\nURL: PUT https://keimvault.vault:8200/v1/auth/kubernetes/login\
nCode: 500. Errors:\n\n* namespace not authorized"
time="2020-11-10T15:20:18Z" level=fatal msg="failed to create vault clienttimeout [10s] during waiting for Vault token" app=vault-env
```

**Comment by gw0** [comment] 2020-11-11 10:44
I am also experiencing an issue with `VAULT_TOKEN=vault:login`, but with a different error (`ERRO[0000] failed to request new Vault token             app=vault-env err="Error making API request.\n\nURL: PUT https://vault:8200/v1/auth/kubernetes/login\nCode: 400. Errors:\n\n* missing client token"`). In `vault-env:1.6.0` it works, but `vault-env:1.7.0` it is broken. I would say the cause of the error is in https://github.com/banzaicloud/bank-vaults/pull/1156/files#r521269241 where defaults are used instead of environment variables for `VAULT_TOKEN=vault:login`.

Therefore, try if it works with `vault-env:1.6.0`.

**Comment by bonifaido** [comment] 2020-11-11 12:59
If you deploy the example according to https://github.com/banzaicloud/bank-vaults/issues/1177#issuecomment-723866019
and exec into the pod it is still working, which is 1.7.0 now:

```bash
kubectl exec -it hello-secrets-7695f8456b-g6csn sh
/ # /vault/vault-env env | grep VAULT_TOKEN
INFO[0000] received new Vault token                      app=vault-env
INFO[0000] initial Vault token arrived                   app=vault-env
INFO[0000] renewed Vault token                           app=vault-env ttl=1h0m0s
INFO[0000] spawning process: [env]                       app=vault-env
VAULT_TOKEN=s.GNE39YBMImx6nrRkDx1L1sZr
```

Probably your deployment is different from the `hello-secrets` one.

I really would like to find out what could be the issue here. 🤞

**Comment by gw0** [comment] 2020-11-11 13:19
> Probably your deployment is different from the `hello-secrets` one. Can you share it @gw0 ?

Oh, you are right, the `hello-secrets` does not have this issue, because it does not modify the default `VAULT_PATH` and `VAULT_ROLE`. It would be a little bit tricky to share my deployment, but try adding these annotations (and configuring Vault accordingly):

```
annotations:
  vault.security.banzaicloud.io/vault-path: "first-k8s-cluster"
  vault.security.banzaicloud.io/vault-role: "my-webhook-role"
```

**Comment by bonifaido** [comment] 2020-11-11 13:51
Fair enough, just submitted: https://github.com/banzaicloud/bank-vaults/pull/1180

**Comment by PeterGrace** [comment] 2020-11-11 17:04
I can confirm that #1180 also corrects my issue.  I can now start a container with the VAULT_LOGIN env var set to vault:login.  When is the next scheduled release?  I want to set a reminder to put my configuration back to the official image once its minted.

**Comment by bonifaido** [comment] 2020-11-12 08:26
Great news! I'm about to release today or at the latest tomorrow. If you don't mind I'm closing this now, because it got resolved.

**Closed by bonifaido** 2020-11-12 08:26 UTC
Labels: vault-env, webhook
