### ISSUE TITLE
Add Vault Namespace to config to allow annotations of a vault namespace

### ISSUE THREAD

**Issue by anoncam** [banzaicloud/bank-vaults#1357] opened 2021-06-15 22:08 UTC
https://github.com/banzaicloud/bank-vaults/blob/de9755fa565dcaf7694e4b66b60994cf2f3fdff3/pkg/webhook/config.go#L28

**Comment by bonifaido** [comment] 2021-06-16 09:05
Duplicate of https://github.com/banzaicloud/bank-vaults/issues/1347

**Closed by bonifaido** 2021-06-16 09:05 UTC
