### ISSUE TITLE
vault-secrets-webhook: TLS handshake error

### ISSUE THREAD

**Issue by devlounge** [banzaicloud/bank-vaults#305] opened 2019-01-25 14:15 UTC
**Describe the bug**
2019/01/25 13:56:01 [WARN] no metrics recorder active
2019/01/25 13:56:01 [WARN] no tracer active
2019/01/25 13:56:01 [INFO] Listening on :443
2019/01/25 13:56:05 http: TLS handshake error from master_node_ip:34468: remote error: tls: bad certificate
2019/01/25 13:56:05 http: TLS handshake error from master_node_ip:34470: remote error: tls: bad certificate
2019/01/25 13:56:15 http: TLS handshake error from master_node_ip:34510: remote error: tls: bad certificate
2019/01/25 13:56:35 http: TLS handshake error from master_node_ip:34616: remote error: tls: bad certificate
...

**To Reproduce**
1. Deploy the chart
2. Wait until the vault-secrets-webhook is running
3. tail the logs

**Expected behavior**
Unknown

**Comment by bonifaido** [comment] 2019-01-25 14:20
How did you install the chart, what kind of Kubernetes version are you running? Do you have any other webhooks or other stuff installed on the cluster which tries to connect to the pod?

**Comment by devlounge** [comment] 2019-01-25 14:33
No, private in-house cluster.

**Comment by bonifaido** [comment] 2019-01-25 14:35
What was the helm command and the chart version when you installed the webhook to the cluster?

**Comment by bonifaido** [comment] 2019-01-25 14:40
Okay, this is the service name format we put into the certificate as hostname:
```yaml
{{ $cn := printf "%s-%s.%s.svc" .Release.Name .Chart.Name .Release.Namespace }}
```
Could you make sure that you use the same domain name format in your cluster for services?

**Comment by devlounge** [comment] 2019-01-25 14:42
I clone the chart repo and installed the 0.3.1 version

`helm template vault-secrets-webhook -f config.yaml --name vault-secrets-webhook --namespace vaults | kubectl -n vaults apply -f -`

**Comment by bonifaido** [comment] 2019-01-25 14:54
Okay I managed to reproduce the issue and pushed a fix for this into banzai-charts, see above ☝️ 

The issue was if I have upgraded the deployment (so run helm again) the certificates have been regenerated, but the deployment didn't restart, so this fix resolves this issue. Thanks for reporting this!

**Comment by devlounge** [comment] 2019-01-25 15:07
When I compare with what istio sidecarinjector webhook does, they mount in the deployment de certs from the serviceaccount secret, and then in their mutatingwebhook configuration, the set caBundle to ""

**Comment by bonifaido** [comment] 2019-01-25 15:15
Have you managed to try the fix? Did it work?

**Comment by devlounge** [comment] 2019-01-25 15:36
Still the same issue.
I have completely deleted everything and reinstalled it. no difference. 
The issue happens on fresh install as well as on update.

**Comment by bonifaido** [comment] 2019-01-25 16:00
Can you please make sure that the same certificate is mounted to the pod what the Secret holds?

**Comment by devlounge** [comment] 2019-01-25 16:05
I added the "cn" label to debug what cn is used to generate the certs:

I get: cn: vault-secrets-webhook-vault-secrets-webhook.vaults.svc
But, clientConfig.service.name has vault-secrets-webhook as value

Could it explain?

**Comment by bonifaido** [comment] 2019-01-25 16:08
I need to check that, but what I can tell is that when I install with the documented way:

`helm upgrade --namespace vaults --install vault-secrets-webhook ./vault-secrets-webhook`

I can't reproduce the issue now. But when I install your way:

`helm template vault-secrets-webhook -f config.yaml --name vault-secrets-webhook --namespace vaults | kubectl -n vaults apply -f -`

I get the errors when posting a deployment onto the API:

```
2019/01/25 16:03:43 [WARN] no metrics recorder active
2019/01/25 16:03:43 [WARN] no tracer active
2019/01/25 16:03:43 [INFO] Listening on :443
2019/01/25 16:04:19 http: TLS handshake error from 192.168.64.38:54388: remote error: tls: bad certificate
2019/01/25 16:04:19 http: TLS handshake error from 192.168.64.38:54392: remote error: tls: bad certificate
2019/01/25 16:04:19 http: TLS handshake error from 192.168.64.38:54394: remote error: tls: bad certificate
2019/01/25 16:04:19 http: TLS handshake error from 192.168.64.38:54396: remote error: tls: bad certificate
2019/01/25 16:04:19 http: TLS handshake error from 192.168.64.38:54400: remote error: tls: bad certificate
2019/01/25 16:04:19 http: TLS handshake error from 192.168.64.38:54404: remote error: tls: bad certificate
2019/01/25 16:04:19 http: TLS handshake error from 192.168.64.38:54406: remote error: tls: bad certificate
```

Have you tried installing it simply with helm, without the kubectl commands?

**Comment by bonifaido** [comment] 2019-01-25 16:13
When I name the release as same as the chart `vault-secrets-webhook`, I can reproduce it even with helm, but if using anything else it works, strange!

**Comment by bonifaido** [comment] 2019-01-25 16:45
I think I have found the issue, the cn was messed up in the certificate if the chart name and the release name matched!

https://github.com/banzaicloud/banzai-charts/pull/631

**Closed** 2019-01-25 17:07 UTC
Labels: bug, chart, community, vault

**Comment by devlounge** [comment] 2019-01-25 17:12
Thanks a lot
We do not want to use tiller ;-)

Anthony

**Comment by wiltonfelix** [comment] 2020-04-15 16:01
Hello @bonifaido, how are you?

I get that error after 3 weeks using the vault and webhook, 

sets:
k8s: 1.14.10-gke.27 
vault: v1.3.2
webhook: v1.0.0

***Values vault***:
```
replicaCount: 1
strategy:
  type: RollingUpdate
image:
  repository: vault
  tag: 1.3.2
  pullPolicy: IfNotPresent

service:
  name: vault
  type: ClusterIP
  port: 8200

ingress:
  enabled: true
  hosts:
   - xxxxxxx
  annotations:
    kubernetes.io/ingress.class: nginx-private
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  tls:
    - secretName: xxxxx
      hosts:
        - xxxxxx


persistence:

  enabled: false

  hostPath: ""

  size: 10G
  accessMode: ReadWriteOnce
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "9102"

labels: {}
  #  team: taki

serviceAccount:
  annotations: {}


resources:
  requests:
    cpu: 100m
    memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector:
  environment: production

tolerations: []

tls:
  secretName: ""

vault:
  customSecrets:
    - secretName: vault-credetials
      mountPath: /etc/gcp
  envSecrets: []
    # - secretName: mysql
    #   secretKey: mysql-username
    #   envName: "MYSQL_USERNAME"
  # Allows adding various custom eenvironment variables directly.
  envs:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /etc/gcp/vault.json
    - name: GOOGLE_PROJECT
      value: vault
    - name: GOOGLE_REGION
      value: us-east1
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
                capabilities = ["create", "read", "update", "delete", "list"]
              }
      - name: allow_production
        rules: path "production/*" {
                capabilities = ["create", "read", "update", "delete", "list"]
              }
      - name: allow_staging
        rules: path "staging/*" {
                capabilities = ["create", "read", "update", "delete", "list"]
              }
    auth:
      - type: kubernetes
        roles:
          - name: apps_default_allow
            bound_service_account_names: default
            bound_service_account_namespaces: default
            policies: allow_secrets
            ttl: 1h
          - name: apps_production_allow
            bound_service_account_names: production
            bound_service_account_namespaces: production
            policies: allow_production
            ttl: 1h
          - name: apps_staging_allow
            bound_service_account_names: apps-staging 
            bound_service_account_namespaces: staging
            policies: allow_staging
            ttl: 1h
    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2
      - path: production
        type: kv
        description: General secrets to production.
        options:
          version: 2
      - path: staging
        type: kv
        description: General secrets to staging.
        options:
          version: 2
  config:
    listener:
      tcp:
        address: '[::]:8200'
        # tls_disable: true
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key

    telemetry:
      statsd_address: localhost:9125

    ui: true
    storage: 
      # file:
      #   path: "/vault/file"
      gcs:
        bucket: "vault-backend"
        # credentials_file: ""
        ha_enabled: "true"
    api_addr: https://vault:8200

  defaultStorage:
    storage:
      file:
        path: "/vault/file"

  logLevel: info

unsealer:
  image:
    repository: banzaicloud/bank-vaults
    tag: 1.0.0
    pullPolicy: IfNotPresent
  args: [
      "--mode",
      "google-cloud-kms-gcs",
      "--google-cloud-kms-key-ring",
      "vault-auto-unseal",
      "--google-cloud-kms-crypto-key",
      "vault-init",
      "--google-cloud-kms-location",
      "us-east1",
      "--google-cloud-kms-project",
      "vault",
      "--google-cloud-storage-bucket",
      "vault-backend"
  ]
  metrics:
    enabled: true
    debug: true
    name: metrics
    type: ClusterIP
    port: 9091
    serviceMonitor:
      enabled: false
      additionalLabels: {}
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "9091"

statsd:
  image:
    repository: prom/statsd-exporter
    tag: latest
    pullPolicy: IfNotPresent
  metrics:
    enabled: true
    port: 9102
    serviceMonitor:
      enabled: false
      additionalLabels: {}
  config:
    mappings:
    - match: vault.route.*.*
      name: "vault_route"
      labels:
        method: "$1"
        path: "$2"

rbac:
  enabled: true
  psp:
    enabled: false

vaultConfig:
  resources: {}

vaultUnsealer:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi

vaultConfigurer:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi

prometheusStatsdExporter:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
```
***webhook*** 
```
replicaCount: 3

debug: true

certificate:
    useCertManager: false
    generate: true
    server:
        tls:
            crt:
            key:
    ca:
        crt:
image:
  repository: banzaicloud/vault-secrets-webhook
  tag: 1.0.0
  pullPolicy: IfNotPresent
  imagePullSecrets: []

service:
  name: vault-secrets-webhook
  type: ClusterIP
  externalPort: 443
  internalPort: 8443

env:
  VAULT_IMAGE: vault:1.3.2
  VAULT_ENV_IMAGE: banzaicloud/vault-env:1.0.0
  # VAULT_CAPATH: /vault/tls
  # used when the pod that should get secret injected does not specify
  # VAULT_CLIENT_TIMEOUT: 10s
  DEFAULT_IMAGE_PULL_SECRET: vault-webhook-gcr
  DEFAULT_IMAGE_PULL_SECRET_NAMESPACE: production

metrics:
  enabled: false
  port: 8443
  serviceMonitor:
    enabled: false
    scheme: https
    tlsConfig:
      insecureSkipVerify: true

volumes: []
# - name: vault-tls
#   secret:
#     secretName: vault-tls

volumeMounts: []
# - name: vault-tls
#   mountPath: /vault/tls

podAnnotations: {}

labels: {}
  #  team: taki

resources: {}

tolerations: []

affinity: {}

## Assign a PriorityClassName to pods if set
priorityClassName: ""

rbac:
  enabled: true
  psp:
    enabled: false

# A list of Kubernetes resource types to mutate as well:
# Example: ["ingresses", "servicemonitors"] 
customResourceMutations: []

customResourcesFailurePolicy: Ignore

# This can cause issues when used with Helm, so it is not enabled by default
configMapMutation: false

configmapFailurePolicy: Ignore

podsFailurePolicy: Ignore

secretsFailurePolicy: Ignore

apiSideEffectValue: NoneOnDryRun

namespaceSelector:
  matchExpressions:
  - key: name
    operator: NotIn
    values:
    - kube-system
  # matchLabels:
  #   vault-injection: enabled

# In case of the K8s cluster version is above 1.15 objectSelector is usable
objectSelector: {}
  # matchExpressions:
  # - key: security.banzaicloud.io/mutate
  #   operator: NotIn
  #   values:
  #   - skip

podDisruptionBudget:
  enabled: true
  minAvailable: 1

```
***logs vault pod***
```
020-04-15T15:26:07.637Z [INFO]  core.cluster-listener: starting listener: listener_address=[::]:8201
2020-04-15T15:26:07.637Z [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=[::]:8201
2020-04-15T15:26:07.637Z [INFO]  core: vault is unsealed
2020-04-15T15:26:07.637Z [INFO]  core: entering standby mode
2020-04-15T15:26:12.687Z [INFO]  core: acquired lock, enabling active operation
2020-04-15T15:26:13.342Z [INFO]  core: post-unseal setup starting
2020-04-15T15:26:13.446Z [INFO]  core: loaded wrapping token key
2020-04-15T15:26:13.446Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
2020-04-15T15:26:13.602Z [INFO]  core: successfully mounted backend: type=system path=sys/
2020-04-15T15:26:13.603Z [INFO]  core: successfully mounted backend: type=identity path=identity/
2020-04-15T15:26:13.675Z [INFO]  core: successfully mounted backend: type=kv path=secret/
2020-04-15T15:26:13.784Z [INFO]  core: successfully mounted backend: type=kv path=production/
2020-04-15T15:26:13.868Z [INFO]  core: successfully mounted backend: type=kv path=staging/
2020-04-15T15:26:13.868Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2020-04-15T15:26:14.679Z [INFO]  core: successfully enabled credential backend: type=token path=token/
2020-04-15T15:26:14.679Z [INFO]  core: successfully enabled credential backend: type=kubernetes path=kubernetes/
2020-04-15T15:26:14.680Z [INFO]  core: successfully enabled credential backend: type=userpass path=userpass/
2020-04-15T15:26:14.680Z [INFO]  core: restoring leases
2020-04-15T15:26:14.680Z [INFO]  rollback: starting rollback manager
2020-04-15T15:26:14.956Z [INFO]  expiration: lease restore complete
2020-04-15T15:26:14.996Z [INFO]  identity: entities restored
2020-04-15T15:26:15.019Z [INFO]  identity: groups restored
2020-04-15T15:26:15.092Z [INFO]  core: post-unseal setup complete
2020-04-15T15:26:16.206Z [INFO]  core: mount tuning of options: path=secret/ options=map[version:2]
2020-04-15T15:26:16.266Z [INFO]  core: mount tuning of options: path=production/ options=map[version:2]
2020-04-15T15:26:16.319Z [INFO]  core: mount tuning of options: path=staging/ options=map[version:2]
2020-04-15T15:28:28.078Z [INFO]  http: TLS handshake error from 10.250.0.120:42148: remote error: tls: bad certificate
2020-04-15T15:28:29.344Z [INFO]  http: TLS handshake error from 10.250.0.120:42152: remote error: tls: bad certificate
2020-04-15T15:28:30.939Z [INFO]  http: TLS handshake error from 10.250.5.20:38862: remote error: tls: bad certificate
2020-04-15T15:28:31.811Z [INFO]  http: TLS handshake error from 10.250.0.120:42154: remote error: tls: bad certificate
2020-04-15T15:28:32.241Z [INFO]  http: TLS handshake error from 10.250.5.20:38864: remote error: tls: bad certificate
2020-04-15T15:28:32.819Z [INFO]  http: TLS handshake error from 10.250.0.120:42158: remote error: tls: bad certificate
2020-04-15T15:28:33.949Z [INFO]  http: TLS handshake error from 10.250.0.120:42160: remote error: tls: bad certificate
2020-04-15T15:28:34.607Z [INFO]  http: TLS handshake error from 10.250.5.20:38874: remote error: tls: bad certificate
2020-04-15T15:28:35.613Z [INFO]  http: TLS handshake error from 10.250.5.20:38878: remote error: tls: bad certificate
2020-04-15T15:28:36.216Z [INFO]  http: TLS handshake error from 10.250.0.120:42164: remote error: tls: bad certificate
2020-04-15T15:28:36.784Z [INFO]  http: TLS handshake error from 10.250.5.20:38880: remote error: tls: bad certificate
2020-04-15T15:28:37.225Z [INFO]  http: TLS handshake error from 10.250.0.120:42166: remote error: tls: bad certificate
2020-04-15T15:28:39.154Z [INFO]  http: TLS handshake error from 10.250.0.120:42172: remote error: tls: bad certificate
2020-04-15T15:28:39.482Z [INFO]  http: TLS handshake error from 10.250.5.20:38884: remote error: tls: bad certificate
```
***webhook***
```
 kubectl logs vault-integration-vault-secrets-webhook-578f655867-bshx4 -n production
time="2020-04-15T15:56:25Z" level=info msg="Failed to request new Vault token Put \"https://vault:8200/v1/auth/kubernetes/login\": x509: certificate signed by unknown authority"
time="2020-04-15T15:56:30Z" level=info msg="Failed to request new Vault token Put \"https://vault:8200/v1/auth/kubernetes/login\": x509: certificate signed by unknown authority"
time="2020-04-15T15:56:32Z" level=fatal msg="failed to create vault clienttimeout [10s] during waiting for Vault token" app=vault-env
```
