### ISSUE TITLE
upgrading version of vault in existing cluster not behaving as expected

### ISSUE THREAD

**Issue by eisjcormier** [banzaicloud/bank-vaults#154] opened 2018-09-12 16:21 UTC
**Describe the bug**
I have an existing bankvault cluster. I'm running Vault version 0.10.4. If I update the cr-etc-ha.yaml file to have a newer version of Vault (0.11.0) and deploy it, my pods are not updated to the new version. I have to manually delete my pods and when they are recreated they have the new version of Vault. 

**To Reproduce**
1. update https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr-etcd-ha.yaml#L7 to have a different version of Vault than you already have deployed.
2. kubectl apply -f cr_etcd_ha.yaml
3. kubectl -n <vault namespace> describe pod vault-0  ( or vault-1)
4. See Image is not the version of Vault specified in the update cr-etcd-ha.yaml file:
~~~
Containers:
  vault:
    Container ID:  docker://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    Image:         vault:0.10.4
~~~

running:  kubectl -n <vault namespace> delete pod vault-0 will cause the pod to get recreated and it will have the correct/expect Image version

**Expected behavior**
 If I update the cr-etcd-ha.yaml file with a new version of Vault and deploy it, my pods perform a rolling update to the new version.

**Comment by bonifaido** [comment] 2018-09-12 18:12
Hi @eisjcormier, which Kubernetes version are you using? I can't reproduce this on my version 1.10 cluster.

**Comment by bonifaido** [comment] 2018-09-12 18:20
this is how my `StatefulSet` looks like after the update from 0.11.0 to 0.11.1 Vault:
```
Name:               vault
Namespace:          default
CreationTimestamp:  Wed, 12 Sep 2018 20:05:59 +0200
Selector:           app=vault,vault_cr=vault
Labels:             <none>
Annotations:        <none>
Replicas:           1 desired | 1 total
Update Strategy:    RollingUpdate
Pods Status:        1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:       app=vault
                vault_cr=vault
  Annotations:  prometheus.io/path=/metrics
                prometheus.io/port=9102
                prometheus.io/scrape=true
  Containers:
   vault:
    Image:       vault:0.11.1
    Ports:       8200/TCP, 8201/TCP
    Host Ports:  0/TCP, 0/TCP
```

**Comment by eisjcormier** [comment] 2018-09-12 19:26
Hi. Thanks for looking into my issue. 

I am running on AWS EKS. K8S version:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:16:17Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:13:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

kubectl describe sts vault

Name:               vault
Namespace:          XXXXX
CreationTimestamp:  Thu, 06 Sep 2018 20:29:24 +0000
Selector:           app=vault,vault_cr=vault
Labels:             <none>
Annotations:        <none>
Replicas:           2 desired | 2 total
Pods Status:        2 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:       app=vault
                vault_cr=vault
  Annotations:  prometheus.io/path=/metrics
                prometheus.io/port=9102
                prometheus.io/scrape=true
  Containers:
   vault:
    Image:       vault:0.11.0
    Ports:       8200/TCP, 8201/TCP
    Host Ports:  0/TCP, 0/TCP
    
 but if you look at the pods, 0.10.4 is what is still running:
 
 kubectl describe pod vault-0
 Name:           vault-0
 Namespace:      XXXXX
 Node:           XXXXXXXXXXXXXXXXXXXXXXXXXX
 Start Time:     Wed, 12 Sep 2018 19:10:39 +0000
 Labels:         app=vault
                 controller-revision-hash=vault-69687f66bc
                 statefulset.kubernetes.io/pod-name=vault-0
                 vault_cr=vault
 Annotations:    prometheus.io/path=/metrics
                 prometheus.io/port=9102
                 prometheus.io/scrape=true
 Status:         Running
 IP:             XXXXXXXXXXXXX
 Controlled By:  StatefulSet/vault
 Containers:
   vault:
     Container ID:  docker://e4e4fb266ab25078bc45493445b64cfd131c42c2973f3c2fd085fd80d1f92bef
     Image:         vault:0.10.4

    
 You'll notice my output of 'describe sts vault' doesn't have any Update Strategy specified. Where does that get defined? Is this not set by default?

**Comment by bonifaido** [comment] 2018-09-12 19:34
Very interesting since the default Strategy is RollingUpgrade: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies

Probably this is an EKS thing, but specifying the strategy explicitly should't hurt, so I will push a fox for this.

**Comment by eisjcormier** [comment] 2018-09-12 19:35
thank you

**Comment by bonifaido** [comment] 2018-09-13 08:10
This seems to be an issue with our current ReadinessProbe setup, which makes sure that only the active Vault instance gets traffic, and the pod is not in `Ready` state. I'm investigating how we could work around this.

**Comment by eisjcormier** [comment] 2018-09-13 12:57
Let me know if you want me to test anything

**Comment by bonifaido** [comment] 2018-09-13 13:50
@eisjcormier I have pushed a fix in #157 for this issue.

**Comment by matyix** [comment] 2018-09-13 14:01
@eisjcormier  Although the Kubernetes bug report attached referencing broken stage this actually applies to not ready pods as well. The rolling upgrade does upgrade all the pods in any other state than the ready one - and unluckily it leaves that out from the upgrade. The workaround is to let rolling upgrades all the not ready pods in the StatefulSet then switch to an upgraded one (ready moves to not ready) - the controller than kicks on to upgrade the old ready one as well.

Hope this was clear enough ...

**Closed** 2018-09-13 14:03 UTC

**Comment by eisjcormier** [comment] 2018-09-13 20:53
Thanks guys. Appreciate the quick turnaround.

**Comment by matyix** [comment] 2018-09-13 20:57
@eisjcormier You are welcome, let us know how it works out for you. Hopefully, the StatefulSet issue will be fixed in the forthcoming K8s version so this will work as it supposed to (without the fix). Thanks for reporting it.

**Comment by bonifaido** [comment] 2018-09-14 08:00
The fix has been released in https://github.com/banzaicloud/bank-vaults/releases/tag/0.2.23.
