### ISSUE TITLE
failed calling admission webhook

### ISSUE THREAD

**Issue by shidoh** [banzaicloud/bank-vaults#286] opened 2019-01-18 06:47 UTC
**Describe the bug**
```
kube-apiserver logging error output: 
"k8s\x00\n\f\n\x02v1\x12\x06Status\x12\xe8\x02\n\x06\n\x00\x12\x00\x1a\x00\x12\aFailure\x1a\xa2\x01
Internal error occurred: failed calling admission webhook
 \"pods.vault-secrets-webhook.admission.banzaicloud.com\": 
the server could not find the requested resource\"\rInternalError*\x9d\x01\n\x00\x12\x00\x1a\x00\"\x90\x01\n\x00\x12\x89\x01
failed calling admission webhook \"pods.vault-secrets-webhook.admission.banzaicloud.com\": 
the server could not find the requested resource\x1a\x00(\x002\x000\xf4\x03\x1a\x00\"\x00"
```
Api-server error after applying manifest. Deployment appears, but pods are not created. After removing the chart, everything works fine

Chart:
```
apiVersion: v1
appVersion: 0.3.27
description: A Helm chart that deploys a mutating admission webhook that configures
  applications to request env vars from Vault Secrets
maintainers:
- email: info@banzaicloud.com
  name: Banzai Cloud
name: vault-secrets-webhook
version: 0.2.1
```

**Comment by bonifaido** [comment] 2019-01-18 08:51
Hi @shidoh,

could you please describe your setup in more details? How did you installed the webhook? Has it been working before? Have you upgraded it?

**Comment by bonifaido** [comment] 2019-01-18 10:19
I'm trying to reproduce, although I don't' have access right now to the same configuration as you have. 

Can you access the webhook pod if you port-forward it to your machine?

**Comment by bonifaido** [comment] 2019-01-18 10:30
And if you hit this endpoint with curl, does it work?

```bash
curl -k https://localhost: 8443/pods
```

**Comment by shidoh** [comment] 2019-01-18 10:41
answer: ```no body found```

**Comment by bonifaido** [comment] 2019-01-18 11:43
Interesting, the same answer is returned for me, but the deployments are working (this shows) that the webhook is up and running and can serve requests (we just sent an invalid request).

Can you describe the replicaset the deployment has created?

**Comment by bonifaido** [comment] 2019-01-18 13:53
Is this this the replicaset from a failed state? :)

**Comment by shidoh** [comment] 2019-01-21 09:33
strange.. but the error no longer repeats, after redeploy chart

**Comment by bonifaido** [comment] 2019-01-21 11:39
@shidoh I'm closing this if you don't mind, please feel free to re-open it again if you encounter the issue!

**Comment by jurgenweber** [comment] 2019-04-09 00:57
I had the same problem, after deleting the chart with ```helm delete secrets-webhook --purge``` and reinstalling the pod now deploys

**Comment by jurgenweber** [comment] 2019-04-10 00:10
I have this again;
```
kubectl describe rs secrets-webhook-vault-secrets-webhook-6df7bb74f9 -n secrets

Warning  FailedCreate  6s (x16 over 3m)  replicaset-controller  Error creating: Internal error occurred: failed calling admission webhook "pods.vault-secrets-webhook.admission.banzaicloud.com": Post https://secrets-webhook-vault-secrets-webhook.secrets.svc:443/pods?timeout=30s: dial tcp 100.70.108.32:443: connect: connection refused
```

api  server logs
```
kube-apiserver-ip-10-10-5-41.ap-southeast-2.compute.internal kube-apiserver-ip-10-10-6-220.ap-southeast-2.compute.internal kube-apiserver 2019-04-10T00:09:38.937966233Z W0410 00:09:38.937771       1 dispatcher.go:71] Failed calling webhook, failing closed pods.vault-secrets-webhook.admission.banzaicloud.com: failed calling admission webhook "pods.vault-secrets-webhook.admission.banzaicloud.com": Post https://secrets-webhook-vault-secrets-webhook.secrets.svc:443/pods?timeout=30s: dial tcp 100.70.108.32:443: connect: connection refused
```

**Comment by bonifaido** [comment] 2019-04-10 15:27
I tried to reproduce this (many times):

- **on minikube with Kubernetes 1.14.0**: I'm unable to reproduce, the deployment always succeeded
- **on EC2 with upstream Kubernetes 1.14.0 (PKE - The Banzai Distribution)**: I'm unable to reproduce,, the deployment always succeeded

I have also tried to emulate the issue, by installing the webhook chart with no replicas, so there is no backend to the webhook:
1. `helm upgrade --install vault-secrets-webhook ./vault-secrets-webhook --namespace secrets --set replicaCount=0`
2. So there are currently no pods in the `secrets` namespace
3. `kubectl scale deployment --replicas 1 -n secrets vault-secrets-webhook`
4. `kubectl get pods -n secrets`
```
NAME                                     READY   STATUS    RESTARTS   AGE
vault-secrets-webhook-56dd9849b7-9xdvt   1/1     Running   0          6m15s
```

So the Pod could be created even tough there were no backends to the webhook service. This could mean two things: the webhook was never called, since the secrets namespace is ignore in the `MutatingWebhookConfiguration`, or it was called just my kube-apiserver doesn't care about the issues. I have checked the api-server logs and there were no issues.

Anyhow, if you have an API server which behaves otherwise possible there are other people as well having the same problem. So we can workaround this with Helm hooks. So the MutatingWebhookConfiguration should have a `post-install` annotation, and we should also create another hook which will delete it, since if it has a Helm hook it is up to the user to delete it.

https://github.com/helm/helm/blob/master/docs/charts_hooks.md

**Comment by jurgenweber** [comment] 2019-04-11 04:18
It dawned on my late last night what you were saying, the [following](https://github.com/banzaicloud/banzai-charts/blob/master/vault-secrets-webhook/templates/apiservice-webhook.yaml#L42) should mean the webhook does not target anything in the namespace.. so then why is it doing it? It must be a k8s version thing. All of your testing is in 1.14.0. I am using 1.11.6.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#webhook-v1beta1-admissionregistration-k8s-io

I followed this to an end and found nothing.

**Comment by jurgenweber** [comment] 2019-04-11 04:19
I found it!

```
$ kubectl get ns secrets -o yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"acronym":"secrets","certmanager.k8s.io/disable-validation":"true","name":"Secrets"},"name":"secrets"}}
  creationTimestamp: "2019-03-07T00:23:44Z"
  labels:
    acronym: secrets
    certmanager.k8s.io/disable-validation: "true"
    name: Secrets
  name: secrets
  resourceVersion: "433222893"
  selfLink: /api/v1/namespaces/secrets
  uid: 44903251-406f-11e9-b226-0a345d48b080
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

notice the 'label' of `name` = Secrets..... I renamed this to 'secrets' and it worked.

**Comment by bonifaido** [comment] 2019-04-11 05:24
Nice, I'm glad it's working now, closing this.

**Closed by bonifaido** 2019-04-11 05:24 UTC
