### ISSUE TITLE
Setting audit to type file with path stdout does not configure vault

### ISSUE THREAD

**Issue by pickledrick** [banzaicloud/bank-vaults#384] opened 2019-03-29 00:48 UTC
**Describe the bug**

When creating an audit of type within a vault's externalConfig with the path set to stdout, configurator does not configure vault as such.

**To Reproduce**

Using the following CR and the bank-vaults installation at version 0.4.6 vault is not configured as expected below

```yaml
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
  namespace: vault
spec:
  size: 1
  image: vault:1.0.0
  bankVaultsImage: banzaicloud/bank-vaults:0.4.6
  supportUpgrade: true
  serviceAccount: vault
  etcdSize: 1
  etcdPVCSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  etcdAnnotations:
    etcd.database.coreos.com/scope: clusterwide
  unsealConfig:
    kubernetes:
      secretNamespace: vault
  config:
    storage:
      etcd:
        address: https://etcd-cluster-client:2379
        ha_enabled: "true"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: https://vault.vault:8200
    telemetry:
      statsd_address: localhost:9125
    ui: false
  externalConfig:
    policies:
      - name: 1_secret_admin
        rules: path "secret/1/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }                  
      - name: 2_secret_admin
        rules: path "secret/2/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: certificates_secret_admin
        rules: path "secret/certificates/*" {
          capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }             
      - name: policy_modifier
        rules: path "sys/policies/acl/*" {
          capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }
      - name: kube_modifier
        rules: path "auth/kubernetes/*" {
          capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }
    auth:
      - type: kubernetes
        roles:
          - name: syncer
            bound_service_account_names: default
            bound_service_account_namespaces: sync
            policies: 
              - certificates_secret_admin
              - 1_secret_admin
              - 2_secret_admin
              - policy_modifier
              - kube_modifier
            ttl: 1h
    audit:
      - type: file
        options:
          file_path: stdout
```

**Expected behavior**
I expect to see the stdout audit configured as such, after performing the cli enable command

➜  ~ vault audit enable file file_path=stdout
Success! Enabled the file audit device at: file/
➜  ~ vault audit list

Path     Type    Description
----     ----    -----------
file/    file    n/a
➜  ~

**Screenshots**

➜  ~ vault audit list

No audit devices are enabled.

**Comment by primeroz** [comment] 2019-03-29 08:55
For reference this works for me, with slightly different versions of componnets though

```
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  annotations:
    app.kubernetes.io/managed-by: kustomize
    mintel.com/env: dev
  labels:
    app: vault
    app.kubernetes.io/app: vault
  name: vault
  namespace: vault
spec:
  bankVaultsImage: banzaicloud/bank-vaults:0.4.15-rc.3
  config:
    cluster_name: vault
    listener:
    - tcp:
        address: 0.0.0.0:8300
        tls_cert_file: /etc/cert-manager/tls.crt
        tls_disable: "false"
        tls_key_file: /etc/cert-manager/tls.key
        tls_min_version: tls12
    - tcp:
        address: 0.0.0.0:8200
        tls_cert_file: /vault/tls/server.crt
        tls_disable: "false"
        tls_key_file: /vault/tls/server.key
        tls_min_version: tls12
    storage:
      gcs:
        bucket: vault-storage
        ha_enabled: "true"
    telemetry:
      statsd_address: localhost:9125
    ui: true
  externalConfig:
    audit:
    - description: STDOUT Audit logging
      options:
        file_path: stdout
      type: file
  image: vault:1.1.0

```


```
kubectl logs -n vault vault-configurer-5b6cdcd778-sqqvn | grep -i audit
time="2019-03-29T08:45:04Z" level=info msg="Already existing audit devices: map[string]*api.Audit{}\n"
time="2019-03-29T08:45:04Z" level=info msg="Enabling audit device with options: api.EnableAuditOptions{Type:\"file\", Description:\"STDOUT Audit logging\", Options:map[string]string{\"file_path\":\"stdout\"}, Local:false}\n"
time="2019-03-29T08:45:05Z" level=info msg="mounted audit device file to file"
time="2019-03-29T08:45:08Z" level=info msg="Mounting secret engine with input: api.MountInput{Type:\"kv\", Description:\"KV for sanbox kubernetes namespace\", Config:api.MountConfigInput{Options:map[string]string{\"version\":\"2\"}, DefaultLeaseTTL:\"\", Description:(*string)(nil), MaxLeaseTTL:\"\", ForceNoCache:false, AuditNonHMACRequestKeys:[]string(nil), AuditNonHMACResponseKeys:[]string(nil), ListingVisibility:\"\", PassthroughRequestHeaders:[]string(nil), TokenType:\"\", PluginName:\"\"}, Local:false, SealWrap:false, Options:map[string]string{\"version\":\"2\"}, PluginName:\"\"}\n"
```

```
vault audit list -tls-skip-verify
Path     Type    Description
----     ----    -----------
file/    file    STDOUT Audit logging
```

The vault-configurator should be configuring your external configs, any error out of it ?

**Comment by bonifaido** [comment] 2019-03-29 09:33
Hi @pickledrick I tried the `cr.yaml` example with an additional config block to the configurator and it seemed to be working for me:

```yaml
+    audit:
+      - type: file
+        options:
+          file_path: stdout
+
```

Vault container stdout:
```json
{"time":"2019-03-29T09:24:25.3691823Z","type":"request","auth":{"client_token":"hmac-sha256:58e7101a1d4e359a5a3214bc41a2dbc6c6dcbc2a3dd2d823aec2473c81b6996b","accessor":"hmac-sha256:666a6dc4e8a899e3b586f8d474394fa67f29bd6aaffdfd46bb51a4b04f6ca05e","display_name":"root","policies":["root"],"token_policies":["root"],"metadata":null,"entity_id":"","token_type":"service"},"request":{"id":"e9902f2b-2fad-1cad-7454-4f17601c19ff","operation":"read","client_token":"hmac-sha256:58e7101a1d4e359a5a3214bc41a2dbc6c6dcbc2a3dd2d823aec2473c81b6996b","client_token_accessor":"hmac-sha256:666a6dc4e8a899e3b586f8d474394fa67f29bd6aaffdfd46bb51a4b04f6ca05e","namespace":{"id":"root","path":""},"path":"sys/audit","data":null,"policy_override":false,"remote_address":"127.0.0.1","wrap_ttl":0,"headers":{}},"error":""}
{"time":"2019-03-29T09:24:25.3702343Z","type":"response","auth":{"client_token":"hmac-sha256:58e7101a1d4e359a5a3214bc41a2dbc6c6dcbc2a3dd2d823aec2473c81b6996b","accessor":"hmac-sha256:666a6dc4e8a899e3b586f8d474394fa67f29bd6aaffdfd46bb51a4b04f6ca05e","display_name":"root","policies":["root"],"token_policies":["root"],"metadata":null,"entity_id":"","token_type":"service"},"request":{"id":"e9902f2b-2fad-1cad-7454-4f17601c19ff","operation":"read","client_token":"hmac-sha256:58e7101a1d4e359a5a3214bc41a2dbc6c6dcbc2a3dd2d823aec2473c81b6996b","client_token_accessor":"hmac-sha256:666a6dc4e8a899e3b586f8d474394fa67f29bd6aaffdfd46bb51a4b04f6ca05e","namespace":{"id":"root","path":""},"path":"sys/audit","data":null,"policy_override":false,"remote_address":"127.0.0.1","wrap_ttl":0,"headers":{}},"response":{"data":{"file/":{"description":"hmac-sha256:94a1f23a559914f0c39a60e238f35c48a061ce1273b2002bd0dafeb64b0169c2","local":false,"options":{"file_path":"hmac-sha256:934a74f6c43af3e3010fb65f47de365253f60e21e83cbbf9878f0ae958dc698c"},"path":"hmac-sha256:8968bcde806757fd5dde3ad22b1d8b5a1dd6986f6810128b378ee4e0d7cb047d","type":"hmac-sha256:e99cc23bc924c06ee9a228f1b5b05989660749d39db1e49094f920a0a609247b"}}},"error":""}
2019-03-29T09:25:16.313Z [DEBUG] rollback: attempting rollback: path=auth/kubernetes/
2019-03-29T09:25:16.313Z [DEBUG] rollback: attempting rollback: path=identity/
2019-03-29T09:25:16.313Z [DEBUG] rollback: attempting rollback: path=secret/
2019-03-29T09:25:16.313Z [DEBUG] rollback: attempting rollback: path=sys/
2019-03-29T09:25:16.313Z [DEBUG] rollback: attempting rollback: path=cubbyhole/
2019-03-29T09:25:16.313Z [DEBUG] rollback: attempting rollback: path=auth/token/
```

Could you see any issues in the logs of the vault-configurer Pod? For me it looks like this:
```
kubectl logs -f vault-configurer-6dd8f46666-rz5tz                                                 (docker-desktop/default)
time="2019-03-29T09:22:08Z" level=info msg="New config file change /config/vault-configurer/vault-config.yml"
time="2019-03-29T09:22:08Z" level=info msg="checking if vault is sealed..."
time="2019-03-29T09:22:40Z" level=info msg="vault is unsealed, configuring..."
time="2019-03-29T09:22:40Z" level=info msg="Already existing mounts: map[string]*api.MountOutput{\"cubbyhole/\":(*api.MountOutput)(0xc000291c70), \"identity/\":(*api.MountOutput)(0xc000291e10), \"secret/\":(*api.MountOutput)(0xc000291ee0), \"sys/\":(*api.MountOutput)(0xc000504270)}\n"
time="2019-03-29T09:22:40Z" level=info msg="Tuning already existing mount: secret/\n"
time="2019-03-29T09:22:40Z" level=info msg="Already existing audit devices: map[string]*api.Audit{}\n"
time="2019-03-29T09:22:40Z" level=info msg="Enabling audit device with options: api.EnableAuditOptions{Type:\"file\", Description:\"\", Options:map[string]string{\"file_path\":\"stdout\"}, Local:false}\n"
time="2019-03-29T09:22:40Z" level=info msg="mounted audit device file to file"
time="2019-03-29T09:22:40Z" level=info msg="successfully configured vault"
```

**Comment by matyix** [comment] 2019-04-04 11:47
Hello @pickledrick - any updates to this? I'm closing it now, please feel free to re-open it if the issue persists for you. In that case, may I suggest joining the [Slack channel](https://community-banzaicloud.slack.com/messages/CFJJW9L94) where we can give more interactive support and debug this together, as we have failed to reproduce it?

**Closed by matyix** 2019-04-04 11:47 UTC
Labels: audit, bug, configurer

**Comment by bonifaido** [comment] 2019-05-24 17:48
Hi @raoofm, yeah, currently audit devices are immutable (also on the Vault API level, please check: https://www.vaultproject.io/api/system/audit.html) so if an audit device is enabled on the given path (if no path is specified the `type` field will become the `path`, in this case `"file"`) you can't configure it.
