### ISSUE TITLE
Both vault reports as leader 

### ISSUE THREAD

**Issue by cu12** [banzaicloud/bank-vaults#215] opened 2018-11-26 14:37 UTC
**Describe the bug**
After upgrading both the operator and my cluster to `0.3.15`, I noticed that both Vault started to report to be the leader, although as I confirmed on CLI only one of them is the leader. This was working correctly in the previous version I used (`banzaicloud/vault-operator:0.3.6` and `banzaicloud/bank-vaults:0.3.4`)

**To Reproduce**
1. Create an HA `Vault` with multiple members
2. Check Prometheus metrics

**Expected behavior**
Only the actual leader reports as the leader.

**Screenshots**
![image](https://user-images.githubusercontent.com/10668222/49020269-52b55400-f190-11e8-903d-d77ac40f6755.png)

**Comment by tarokkk** [comment] 2018-11-27 12:52
What you see there is the by-design result of the Prometheus time series database. The exporter reports `vault_sys_leader` with value `1` if the member is a leader, otherwise it don't report anything. It means that choosing proper `time range` is essential (or for example Grafana single stat / current value) because prometheus will show the **last valid** scrape data. That means you get different results for a **1 hour** span and for the latest values (about scrape time range). You can change time range at the **Graph** tab on prometheus. If you want to get your hands dirty with prometheus and Grafana may I suggest you to read our blogs regarding these topics https://banzaicloud.github.io/tags/monitoring/

P.S: We will update the metrics exporter to report 0 for non-leader members as well so this won't be an issue with late release

**Comment by cu12** [comment] 2018-11-27 17:43
Hi @tarokkk 

Thanks for taking a look at this, although I don't think this is a Prometheus issue as both scraping targets are reporting `vault_sys_leader 1`

```
/ # curl -s http://10.244.11.83:9091/metrics | grep vault_sys_leader
# HELP vault_sys_leader Is the Vault node the leader.
# TYPE vault_sys_leader gauge
vault_sys_leader 1

/ # curl -s http://10.244.8.116:9091/metrics | grep vault_sys_leader
# HELP vault_sys_leader Is the Vault node the leader.
# TYPE vault_sys_leader gauge
vault_sys_leader 1
```

Actually as I see you have the conversion of boolean to float here `https://github.com/banzaicloud/bank-vaults/blob/743cb0b63278a76207745a9f72f221f21e7fbf47/cmd/bank-vaults/metrics.go#L83` and it's being used, so I don't really get why it's not zero as should be.

**Comment by bonifaido** [comment] 2018-11-28 15:56
I have reported the issue, https://github.com/hashicorp/vault/issues/5863
The workaround fix for this is incoming soon.

**Comment by jefferai** [comment] 2018-11-28 16:42
Not a bug on the Vault side, sorry.

**Comment by bonifaido** [comment] 2018-11-29 06:51
The fix is final now, I found that another operation was changing the address of Vault inside the client which reports the metrics, that caused the confusion, sorry for that @jefferai @cu12 !

**Closed** 2018-11-29 10:12 UTC
Labels: bug, community

**Comment by bonifaido** [comment] 2018-11-29 10:14
@cu12 the fix has been released in https://github.com/banzaicloud/bank-vaults/releases/tag/0.3.17

**Comment by cu12** [comment] 2018-11-29 12:21
Yay! Thanks, testing it already :) Will come back with the results.
