### ISSUE TITLE
[chart/bank-vaults/operator] Helm upgrade fails with Helm 3

### ISSUE THREAD

**Issue by jshrack-ssi** [banzaicloud/bank-vaults#772] opened 2019-12-01 04:09 UTC
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
When performing an upgrade to an existing chart using Helm 3 the following error is displayed:

helm upgrade -f values.yaml vault-operator banzaicloud-stable/vault-operator

Error: UPGRADE FAILED: cannot patch "vault-operator" with kind Deployment: Deployment.apps "vault-operator" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"vault-operator"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

**Expected behaviour**:
Successful upgrade of the existing release

**Steps to reproduce the bug**:
1) Modify Helm chart overlay values.
2) Issue: helm upgrade -f values.yaml vault-operator banzaicloud-stable/vault-operator

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.13
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- bank-vaults version (e.g. 0.4.17): bank-vaults-operator-0.5.1/vault-operator-0.5.5
- Install method (e.g. helm or static manifests): Helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by bonifaido** [comment] 2019-12-03 11:56
I'm not sure if this is a bug in the helm chart. TBH I can't reproduce this right now, probably I miss some details what has changed in values.yaml.

**Comment by jshrack-ssi** [comment] 2019-12-03 21:52
Of course, make sure you are using Helm 3, not Helm 2. Install an old version of the chart and then attempt to upgrade to the most recent release. I suspect it could be the result of the new 3-way merge strategy in Helm 3.

**Comment by bonifaido** [comment] 2019-12-04 09:19
I'm using Helm3 of course for testing this, but without the content of values.yaml this can't be reproduced, trust me.

**Comment by jshrack-ssi** [comment] 2019-12-07 18:25
Hi @bonifaido. Thanks for your response. I suspect this isn't an issue with the values.yaml so much as the root cause sources from the underlying Helm templates. It seems more recent versions of the chart updated values which are seen as immutable by Helm 3. I understand it's difficult to reproduce. Worst case is I have to delete or force the upgrade of the chart. Could you lend some guidance as to an approach that would not destroy my existing Vault cluster in order to update the vault operator chart?

**Comment by bonifaido** [comment] 2019-12-09 10:08
Hi @jshrack-ssi !

What version of the operator chart are you using now, and what version are you planning to update?

**Comment by jshrack-ssi** [comment] 2019-12-09 14:38
@bonifaido My current vault-operator deployment is on chart version 0.2.17 and I want to update to 0.5.5. The latter is the version upgrade that is failing due to the immutable chart label selector.

**Comment by bonifaido** [comment] 2019-12-09 14:48
Oh I see, 0.2.17 is quite an old version, but no problem:

I just tested this locally and it works fine just as an upgrade path (all with helm 3):
```bash
helm upgrade --install --wait vault-operator banzaicloud-stable/vault-operator --version 0.2.17

# in the bank-vaults repo
kubectl apply -f operator/deploy/rbac.yaml
kubectl apply -f operator/deploy/cr.yaml

# wait for the "old" vault instance to come up

# delete the deployment of the operator to overcome the labelSelector immutability stuff
kubectl delete deployment vault-operator
helm upgrade --install --wait vault-operator banzaicloud-stable/vault-operator --version 0.5.5

# delete the vault statefulset, since the new operator creates a quite different version now (
kubectl delete statefulset vault

# After a few seconds my "new" vault statefulset just came up with a healthy pod.
```

**Comment by bonifaido** [comment] 2019-12-13 14:45
Did this work @jshrack-ssi ?

**Comment by jshrack-ssi** [comment] 2019-12-13 19:46
@bonifaido I just got a chance to work on this right now. A couple of follow-on questions. The immediate "upgrade" of the chart to 0.2.17 worked fine to bring Helm back to a non-fail state. With regard to the following steps: 

1) As my existing Vault cluster is already running fine is there any need to apply the cr.yaml?
2) Will the deletion of the vault-operator deployment destroy my standing cluster? If so, would it be recoverable with the same unseal keys and backend DynamoDB store?
3) Would removal of the existing statefulset preserve the unseal/DynamoDB tables associations to essentially resume existing Vault cluster state?

Sorry for all the questions, there's a high investment of development time into the Vault cluster so I need to validate the expected outcomes of these actions before I undertake them.

Thanks so much for all your help!

**Comment by bonifaido** [comment] 2019-12-17 18:43
1. No, this is not needed in this case (this was just an example from me :) )
  2. No, the vault-operator Kubernetes deployment deletion shouldn't harm the data (the chart deletion does it of course since it removes the Vault CRD as well), you can use the same data again.
  3. Yes, the statefulset deletion just removes the Vault Pods and nothing else, in the next cycle, the operator (if running) will recreate it again.

**Comment by jshrack-ssi** [comment] 2020-01-05 21:06
This process worked very well. Thank you, I appreciate the guidance!

**Comment by bonifaido** [comment] 2020-01-06 07:30
Nice to hear that! Did this solve your issue @jshrack-ssi ? Can we close this one?

**Comment by jshrack-ssi** [comment] 2020-01-06 07:39
Please do so. Thanks again for the assistance.


________________________________

**Comment by bonifaido** [comment] 2020-01-06 07:40
Closing with: https://github.com/banzaicloud/bank-vaults/issues/772#issuecomment-563272124

**Closed by bonifaido** 2020-01-06 07:40 UTC
Labels: chart, operator, question

**Comment by dankirkpatrick** [comment] 2020-01-31 14:52
I'm getting this error with helm v3 and the chart version 0.6.4.   I believe this is the latest version of the chart.

Here's my command:

```
$ echo ${VAULT_CHART_VERSION}
0.6.4

root at 7c5de6095c44 in /provision on [onprem-02]
$ helm install vault-operator -n vault --version=${VAULT_CHART_VERSION} --set=etcd-operator.enabled=true --set=replicaCount=3 --set=etcd-operator.etcdOperator.replicaCount=3 --set=etcd-operator.etcdOperator.commandArgs.cluster-wide=true banzaicloud-stable/vault-operator --wait
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
```
The chart remains in a pending state and never installs.

**Comment by bonifaido** [comment] 2020-01-31 14:55
And what is the error message in your case? `skipping unknown hook: "crd-install"` is coming from the etcd-operator chart, and it is not an error.

**Comment by dankirkpatrick** [comment] 2020-01-31 15:30
So this is because of the etcd-operator the vault chart depends upon?  It never progresses once this error is seen.

```$ helm ls -a -n vault
NAME          	NAMESPACE	REVISION	UPDATED                                	STATUS         	CHART               	APP VERSION
vault-operator	vault    	1       	2020-01-31 14:40:12.631449153 +0000 UTC	pending-install	vault-operator-0.6.4	0.8.0      
```

**Comment by bonifaido** [comment] 2020-01-31 16:40
We continued on slack, it turned out to be a networking issue.
